version: '3'

services:

  backend_postgres:
    image: "postgres:${BACKEND_POSTGRES_TAG}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./enviroment/backend/postgres

  auth:
    env_file:
      - ./enviroment/backend/postgres
      - ./enviroment/backend/django
    build: ./auth/
    volumes:
     - ./auth/:/code
    depends_on:
     - backend_postgres
    ports:
      - "8001:8000"
volumes:
  pgdata:
