version: '3'

services:

  nginx:
    image: foothub/nginx:latest
    ports:
      - "8000:80"

  auth_postgres:
    image: postgres:9.6
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    env_file:
      - ./enviroment/auth/postgres

  auth:
    image: foothub/auth:latest
    env_file:
      - ./enviroment/auth/postgres
      - ./enviroment/auth/django

volumes:
  auth_pgdata:
